sonar.projectKey=obligatoriodevopsgrupo13_retailstore-infra
sonar.organization=obligatoriodevopsgrupo13

sonar.projectName=retailstore-infra
sonar.sourceEncoding=UTF-8

sonar.sources=.

sonar.exclusions=**/.terraform/**,**/terraform.tfstate,**/terraform.tfstate.backup,**/*.tfstate,**/*.tfstate.*,**/.github/**,**/.cache/**,**/node_modules/**
